version: "3.8"

services:
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8001:8000" # 8001 - חיצוני, 8000 - בתוך הקונטיינר
    environment:
      - PORT=8000
      - MONGO_URI=mongodb://mongo:27017/auth
      - SESSION_SECRET=super-secret
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth-service

volumes:
  mongo-data:
