version: "3.8"

services:
  gateway:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8001:8000"
    environment:
      PORT: 8000
      MONGO_URI: ${MONGO_URI}
      USERS_COLLECTION_NAME: ${USERS_COLLECTION_NAME}

    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
